
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myappdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build: .
    image: ggronda/webapp17
    container_name: spring-app
    ports:
      - "8443:8443"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Reminder!!!!  OLLAMA_HOST=0.0.0.0 ollama serve in the vm
      # before using the docker compose up bc if not the host.docker.internal will not work
      OLLAMA_URL: http://host.docker.internal:11434
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - app-files:/app/files  # This matches your upload.path
volumes:
  mysql-data:
  app-files:

networks:
  app-network:
