version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password  # Cambié la contraseña a 'password'
      MYSQL_DATABASE: myappdb
    ports:
      - "3307:3306"  # Cambié el puerto externo a 3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: spring-app
    ports:
      - "8443:8443"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/myappdb  # Aquí no cambian los puertos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password  # Aseguré que la contraseña sea 'password'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
